[package]
name = "tests"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rangemap = "1.6.0"

[dev-dependencies]
libc.workspace = true
rustix = { workspace = true, features = ["fs"] }
serde = { workspace = true, features = ["derive"] }
tempfile.workspace = true
toml = "0.8.23"
